apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:YKORkSN0Cm/Z5Rx45HuZ4z/q+jqjEHwxYXnPTG61fQ2FUrmlMMkpqg==,iv:hwsc1pqZ5epObEx+n28Burgj0etJF+dietz4Qsg036s=,tag:MaY7dQ8MUF3whIygsRgJTw==,type:str]
sops:
  age:
    - recipient: age1n8lspdc2k4pvcwnm90zu9wl9sfcj62sj56nzaeed7st6hc23f3ksufc5wf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3TmI5bzgzMlZKOHh0MEE2
        TlU4NVUvK0JHbUFCa0ZPTGNCZk1DU0JNR1RFCjF4S0YydlJXd2dLdi9sYUx5ZlF1
        TldGdk9DakRBZUo2Y3FKRFVhbWJaRlkKLS0tIDhWNFNqbUhESFJvYkVUNlE5MVBW
        aVB3cUNtS2txOTFCMjRncTV0b2diUmcKKZq9m8fpqo594ioO0ze0b87yG4A7/IS7
        HB2ZeY33bFG3fsip6RizTqVF5cNcyefBI0XAZDGk61VW4yqtHWnvGA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-06T10:06:43Z"
  mac: ENC[AES256_GCM,data:0FXG/rXmZ23Y0lNgUdGFFmJNtlmM63OHoOYv7jyFyfNhuyFM6K9VqE95iD7bIOl7BJXAKF9eA3kwwt/HI2twleIzyM0qm0KueQNLk1J101WNjaOKIGcLJBIu7ygCGKkacxS+rH5EF1ucY5BuR1aYoWiWkJ53fqppDbgxutHN/cs=,iv:MW/r0vT/sT3XyAKFH21HjlaLivBcFzYf/IJQBJ6Csro=,tag:7ELcw2UUWncbIlhoU7urvw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
