apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:Itv+XiJC3beY7yzjV4Ds,iv:bNj2XDZDXD8616cHnm08Mfo/SjwuEoUk6JtAu1AbPS8=,tag:bYMpneN8Oxicw0z00by6gQ==,type:str]
sops:
  age:
    - recipient: age1n8lspdc2k4pvcwnm90zu9wl9sfcj62sj56nzaeed7st6hc23f3ksufc5wf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBncjVPbVdBUGVLVUJscDV4
        ekVkbFVobGRzTGRWS09aRFRlZnVBOS9LWHhBCk84eXdTNmlibERnRk1KK1Q4dzdK
        RmpOUkZCbDZJQTlFZWdLWVd3WXowbUkKLS0tIFNST0w0RnQ1L3lCYnB5WWQvQ21u
        bjVUQ0plbXlMQS9pbnl2Y3NVeDMzMEkK/9xPJv6Izo8kRMJf7qPZP+BQbDFAVeQP
        uKFtMFs7Wi4mJUEYkxheIGHkbTSoN+IvYWpgN/itLFoaE5l6EQbCUg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-06T10:06:43Z"
  mac: ENC[AES256_GCM,data:gl51l293636HQnkwvZzvhdZke5OQxGZeH0Xkp7/wW6izeC9gWZVDixP0SlIDKZ+MMj4R1ArSoK0iu1VdSOA4d5eR3Pjt1bQ4Eqkl8JTOQgFslHXF8HHORVZdqnc2MmykhOlfzmCc3arn3hxOqPXsbbt9SsDYz1UouN9ZEbQ67FI=,iv:7vQYipiyI+jPONakRAx2c44Umanq6GVVrYhd2gGBLL8=,tag:M6QTz6m1aSYxtDXC1/esBQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
