apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:jw1YMM8etInu9bn2Ria4pcgKnqfd9WWjDil1MYx4rvI=,iv:RxxpqZJcm5VQLy+HDnPiHckw1mWOXMefgCpZJP77GWQ=,tag:+Nzb7T6OZ/z1+aMJtQU4iw==,type:str]
sops:
  age:
    - recipient: age1n8lspdc2k4pvcwnm90zu9wl9sfcj62sj56nzaeed7st6hc23f3ksufc5wf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBid1lZeklIWE1HYXNIRWRq
        Y256WVZiYlRJUWxlc0xLZ1ZibDdFQk96dXpJCkJXMlFQcFMrampQYjVjWEhvNnNO
        TkhnRDhoZjA0WDA4QllZQlNYZWFGVlEKLS0tIEtyQjlYSlJpWnZBdjkrTEpEeXI5
        czNGWGRSK1kwYU1RQ2VEbytEcyt3cWsKAYUnlo8ITqFWCTc0hHDkAnzKH8REBxYD
        yuqyg7wSb5NgdGCdmvfLOQr+zCUsSfGM8U86kCDg42oB1qCejS0Dlw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-06T10:06:43Z"
  mac: ENC[AES256_GCM,data:kbUpeS3xtTtZCcr6cQ1DC6pHTRl/2qcKIl4RuXRpN8A9SF45s79xrXOjahomsFyH8a6U1I2wD497fUzrN9T9rPWODx7D7s2GCC/PN1u9/EbwYyVFJu+6f24Ck/R6M/S3H7yGZZIvWjz3dTTjwf5CwqXNzOKXWmwPvVBywZ+ywAA=,iv:r+ZnVIoR6OQiVRG2wW2Pd2GsZ75TPI9TrTt3BmLKEOE=,tag:aGNAgRhKRgFupYdIyVHMDw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
