apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:pCc494KZ0FtgfC9SgywcKLGelMxkTv7sTR4O/XTzfrg53XTDeLpKkK4uhZ3IHvL1mui73mzodHf1/ORvUwclaKvsf2J8OQwNucsdhAyZEKKDmHuXg3kUg/kMc0p4wqWswJ7vcfMGw1/WT9SRSiuPTD2s6EXb+UiWl7RcByuWwVBxlAeJeJQviH1rw9KDXuUURtrQm6BxdpWkRwRlTNncTKNWwy+IPZEgHa9RikfSZpLwYPXm,iv:uNOWdM7MoqTp3vs117N6OWcMSU5N7goESm7Kj8lvDcM=,tag:VWh+5OgNsVIzws2J8ZYcNA==,type:str]
sops:
  age:
    - recipient: age1n8lspdc2k4pvcwnm90zu9wl9sfcj62sj56nzaeed7st6hc23f3ksufc5wf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRMVZSczVISkVqKzV2c3c5
        ZzVEYmNHa3lkempxeEV4cjAzWWtpa1RIZERFCmpTVjFrUUptK1Z0VlZJVTRDNUgx
        K3dubTFaZWhjdXpGZDh1YzBNRk1pTmMKLS0tIHMrVGNjWVpJRUhHV21yVWh1OFha
        RXFSU0FvdFpyOXZnZEx5MmhsRXRzNXcK1ixzVc+OvKqvXCZgVtYXieGd6fMJxK/V
        ZiUsYxTfwZt58sn6TCdmoq19K6IjAADVs7Z5dtpJuMmQB1o26n1Tag==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-06T10:06:43Z"
  mac: ENC[AES256_GCM,data:9E4qN8YvsymsxCJFtT6H3DrQRE3Tzrux89rjQeC8SMjTJCXUS9/hvUbCZIVu0q1J6urXmTqPgGg4G4Zwm3Uj45BqO6g1oHje6kQbyhXOu8NQWfSpgK1RJO0/EXH/1Sa40uvobYgWBH+KEbEiGxV++BSX5iBhwftGMUKEpLY6fII=,iv:6mTiBnjMLx7yElKuOvcnkrix36xz2r4zToI05dLvt20=,tag:sGQbPJZ7zLQ2kN+Pm89GUA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
