apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:bsgrrk+UI48hCSDNBtNdh4Pjg3mOsxmngQG79do9+GCKbxVX8G3YaQ==,iv:10Q2/dFz2I7gaPjrOT3SesJA3KWhCkAIFKpYoHs66aw=,tag:lA3RNPuObE4jCzglcl8YpQ==,type:str]
sops:
  age:
    - recipient: age1n8lspdc2k4pvcwnm90zu9wl9sfcj62sj56nzaeed7st6hc23f3ksufc5wf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5SGl5MFgyNnZ0QUJibFo0
        cS9iNkRuWkh3V0lCT2VQWURuR3lSd09pbUZNCjJ6SkZFcUY1NU5oT09XcmhTYUlO
        UnhQNy9kSVVJWGdUK25iY0gvbVZRZ1EKLS0tIEZidEdWZVZLUWx2bjNpbG50NEpw
        TXNxcFV5cC90Rm9xWjBOYk1EbmFIc2cKo08gJZcNYnZuX/TIuuRgVywYHBFL940C
        omR6lBl+mxsma4Bpgzj8OxtEvaL9I1FZWEqUfbBnPrArasnMpFFxAQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-06T10:06:43Z"
  mac: ENC[AES256_GCM,data:MvnotpvvoqWkIqXXYoPWeYwGrSivLLcVh1+OUQtSBKJRNw6IeCu0ojffdS3fs7FnFQSepWhLPcKI17aUyhAX7UpBXZmFQNlEftmEuS0vv9WsIDfAG6beZZsbPJutScGKAP4CV3IuIFGEZvZE+RWjuzQuZG2VzuIHKdZX3U7kW90=,iv:pTy4Bhx8KGRjrfLrKwxrDI5UfMvExa4HLCmMbN4Y1T8=,tag:1YPk+fTBf7QFWMJV5Amfng==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
